repository: Jerrywang959/Website_Guide
repository_url: https://github.com/Jerrywang959/Website_Guide

timezone: Asia/Shanghai
lang: zh_CN

title: Jerry's Guide
alias_en: Jerry's Guide
alias_cn: Jerry的网站导航
description: A Navigation Website for Jerry
keywords: Website, guide
url: https://guide.jerry.top
established_at: "2020-05-24T00:00+08:00"

author: jerrywang
author_url: https://jerrywang.top
organization: #TEELAB
organization_url: #https://teelab.net
contact: #contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor